### ISSUE TITLE
[Suggestion] Saving converted IPAs

### ISSUE THREAD

**Issue by AymenKcm1** [sourcelocation/DebToIPA#10]
Hi, 

I think having a tab where we can find successful converted IPA files in the app would be very useful, now if we convert an IPA and it works if we want to save the IPA we have to convert it again, and some apps take some time to convert.

So it would be better to save them, and if they don't work we simply delete them. 

Of course this is not a priority, if you have the time and can add it please do. 

Thanks.

**Comment by RavanGami** [comment]
![image](https://user-images.githubusercontent.com/114746710/196035237-cf1e264c-9e60-4f34-9115-ca106c44ac27.png)

**Comment by AymenKcm1** [comment]
I don't think you understood my suggestion: 

Your screenshot indicates that the selected deb file is unsupported and cannot be converted, when I was talking about saving **SUCCESSFULLY CONVERTED IPAs**. 

I know we can save them now elsewhere (like in Files or other apps) and then open them from there to install with TrollStore (giving that we don't do it when converted)

I think having them saved in the DebToIPA app would be easier and very helpful in managing and sharing IPA files.

I hope you understand now my request.

Have a good day 😊

**Comment by sourcelocation** [comment]
Hi, thanks for the suggestion. I'll add this feature in the next major update

**Comment by sourcelocation** [comment]
Added in 1.1, 0ee13fb810a9700b3689d507b763af5053e9b347. It's a pre-release and most bugs will be fixed. I won't close this issue for now

**Comment by AymenKcm1** [comment]
Thank you 😊

**Comment by anupvadhul** [comment]
Hi there. I have been able to convert one the deb files names “easydialer” and I was eager to convert other deb like safariplus and carplay enable for which I am getting above error when tried. Can this be fixed. Appreciate if its done
![Uploading AFB917CE-9DAE-43D0-9DDC-D1F56BE66E0C.png…]()

**Comment by AymenKcm1** [comment]
@anupvadhul You can't convert tweaks, only apps, and even that doesn't work with every app since many has dependencies that can only be installed on jailbroken devices.

PS: Some of the converted apps that didn't work do work when injecting Cydia Substrate to the IPA. 

![image](https://user-images.githubusercontent.com/67245917/196626219-1e2405f1-ebc9-43b8-9195-49f49d2f8f89.jpeg)
