### ISSUE TITLE
Error when trying to convert Cydown Deb to IPA

### ISSUE THREAD

**Issue by ACHIYA96** [sourcelocation/DebToIPA#2]
“Unsupported compression. This is a bug with the app. Please create an issue on Github with the name of tweak/app. Thanks!”

**Comment by namhai1994** [comment]
Tks

**Comment by RavanGami** [comment]
![image](https://user-images.githubusercontent.com/114746710/195968892-0b2e2fe7-c627-43c2-97a4-f5031defa5e9.png)

**Comment by sourcelocation** [comment]
@ACHIYA96 Thanks for reaching out, I’ll try to support the algorithm in the near future, though I think the app wouldn’t work. Still worth a shot

**Comment by AymenKcm1** [comment]
CyDown does have an app, but its functionality is integrated INSIDE package managers (Cydia, Zebra...) so even if you somehow managed to get a working IPA it would be USELESS.

**Comment by ACHIYA96** [comment]
@sourcelocation Appreciate your effort.

**Comment by sourcelocation** [comment]
Updated the app, try downloading 1.0 and see if it works

**Comment by ACHIYA96** [comment]
Now it compiles and can install with Trollstore. But it crashes. I think @AymenKcm1’s reason should be the culprit. Anyhow, thank you for your great work!
