### ISSUE TITLE
don't work

### ISSUE THREAD

**Issue by jeje9527** [sourcelocation/DebToIPA#3]
i have waited 10 min ,igamegod.deb(size:39M
![EA003F1F-D2A6-4597-885A-037A8BE4C466](https://user-images.githubusercontent.com/48116066/195973342-44ee4dd8-be88-4d54-884c-26f255f91814.png)
)

**Comment by AymenKcm1** [comment]
Get the working iGameGod IPA from here

https://github.com/34306/TrollStoreiPA/releases/tag/TS_iPA

👍

**Comment by jeje9527** [comment]
> Get the working iGameGod IPA from here
> 
> https://github.com/34306/TrollStoreiPA/releases/tag/TS_iPA
> 
> 👍

thank you
