### ISSUE TITLE
Error when decrypting Iridium

### ISSUE THREAD

**Issue by Dr-Sauce** [sourcelocation/DebToIPA#4]
https://github.com/Lakr233/Iridium

![9C0095C6-00E9-4F25-B9E9-E9432BAF7444](https://user-images.githubusercontent.com/82555878/195973813-ad4c4ad2-7ec2-4908-bae5-e6f14d922ae9.png)

**Comment by sourcelocation** [comment]
@Dr-Sauce Thanks for reaching out, I’ll support the compression algorithm in the near future.

**Comment by sourcelocation** [comment]
@Dr-Sauce can you please try using 1.0 and see if it works? thanks

**Comment by mihai91** [comment]
> @Dr-Sauce can you please try using 1.0 and see if it works? thanks

It works on the latest version
