### ISSUE TITLE
No symbolic link extraction support. CallLogPro fails to convert.

### ISSUE THREAD

**Issue by AymenKcm1** [sourcelocation/DebToIPA#5]
![image](https://user-images.githubusercontent.com/67245917/195984192-1a80c292-4930-4b1e-bc6e-9bd19a1151d2.jpeg)

App name : CallLogPro (iOS 14 to 8)
Version : 14.2-beta-4

Deb from [Here](https://www.ios-repo-updates.com/repository/iarrays/package/com.iarrays.calllogpro8/)

Created this issue because it gave me the error indicating that it might be an issue with DebToIPA, but it might be an error due to lack of dependencies later if DebToIPA is updated and succeeds in creating the IPA 😅

**Comment by sourcelocation** [comment]
Hi, thanks for creating this issue. I’ll update the app in a couple of hours, shouldn’t be hard to fix

**Comment by sourcelocation** [comment]
Fixed in 1.0.2. https://github.com/sourcelocation/DebToIPA/commit/65043c1db968b9bb6e7481415125629754d32eb0

**Comment by AymenKcm1** [comment]
> Fixed in 1.0.2. https://github.com/sourcelocation/DebToIPA/commit/65043c1db968b9bb6e7481415125629754d32eb0

Thanks for that, but as I predicted now it does convert to IPA and installs but it crashes, nothing to do with DebToIPA, it is most likely dependencies issues. 

Thanks again.
