### ISSUE TITLE
[Suggestion] Add a Settings / About tab

### ISSUE THREAD

**Issue by AymenKcm1** [sourcelocation/DebToIPA#7]
It would be very useful to add a dedicated Settings / About tab to add any options & toggles and credits to keep the main screen clean. 

And it would be even more useful to add an **update checker / downloader** (Like in TrollStore settings) to quickly update the app without have to open the GitHub link every time there's an update. 

![image](https://user-images.githubusercontent.com/67245917/195994321-c91c3b4e-7436-4a62-981c-7d7520e917b8.jpeg)

Thanks for making this app and for working to make it better. 

Good luck.

**Comment by sourcelocation** [comment]
Hi, thanks for the suggestion!

**Comment by sourcelocation** [comment]
Hi, thanks for the suggestion. I plan on making an all-in-one utility for TrollStore in the near future, and it will have this tab.
