### ISSUE TITLE
Some kinds of converted deb apps cannot be launched but with a flashback and exit.

### ISSUE THREAD

**Issue by Camwinny** [sourcelocation/DebToIPA#9]
The tested deb is as follows:
App name: Filza
App Version: 3.9.7
The deb file is: [filza_3.9.7-2_iphoneos-arm.deb.zip](https://github.com/sourcelocation/DebToIPA/files/9793554/filza_3.9.7-2_iphoneos-arm.deb.zip)

**Comment by RavanGami** [comment]
filza not work

**Comment by Camwinny** [comment]
> filza not work

Is there any reason?

**Comment by sourcelocation** [comment]
Hi, filza is known to not work with these kinds of tools. You can download Filza ipa straight from their website (https://www.tigisoftware.com/default/?p=439)
